oceans_topaz:
  hosts:
    topaz1:
      ansible_host: 170.64.202.167
    topaz2:
      ansible_host: 209.38.24.131
    topaz3:
      ansible_host: 170.64.202.246
  vars:
    ansible_port: 3346
    ansible_user: agent_topaz
